const express = require('express');
const router = express.Router();
const auth = require('../middleware/authMiddleware');
const { generatePDF } = require('../actionHandlers/pdf');
const Session = require('../models/Session');

router.use(auth);

// POST /api/pdf/generate - Generate PDF from chat history or content
router.post('/generate', async (req, res) => {
  const uid = req.user && req.user.uid;
  if (!uid) return res.status(401).json({ error: 'unauthorized' });

  const { type, sessionId, content, title } = req.body || {};
  
  try {
    console.log('[PDF] Generating PDF:', { type, sessionId, uid });
    
    let pdfContent = '';
    let filename = '';
    let chatHistory = null;
    
    if (type === 'chat' && sessionId) {
      // Generate PDF from chat history
      const chatSession = await Session.findOne({ sessionId, userId: uid });
      if (!chatSession) {
        return res.status(404).json({ error: 'session_not_found' });
      }
      
      filename = `chat-history-${sessionId}-${Date.now()}.pdf`;
      pdfContent = formatChatHistory(chatSession.messages, title);
      chatHistory = chatSession.messages;
      
    } else if (type === 'content' && content) {
      // Generate PDF from custom content
      filename = `${title || 'document'}-${Date.now()}.pdf`;
      pdfContent = formatContent(content, title);
      
    } else {
      return res.status(400).json({ error: 'Invalid request. Provide type=chat with sessionId OR type=content with content' });
    }
    
    // Generate PDF
    const pdfResult = await generatePDF({
      filename: filename,
      content: pdfContent,
      query: title || 'PDF Generation',
      chatHistory: chatHistory
    }, uid);
    
    console.log('[PDF] PDF generated successfully:', pdfResult.data?.filename);
    
    res.json({
      success: true,
      filename: pdfResult.data?.filename,
      downloadUrl: `http://localhost:4000/api/downloads/${pdfResult.data?.filename}`,
      size: pdfResult.data?.size || 0,
      timestamp: new Date().toISOString()
    });
    
  } catch (error) {
    console.error('[PDF] Error generating PDF:', error);
    res.status(500).json({ error: 'Failed to generate PDF', message: error.message });
  }
});

function formatChatHistory(messages, title) {
  let content = '';
  
  if (title) {
    content += `${title}\n`;
    content += '='.repeat(50) + '\n\n';
  }
  
  content += 'Chat History\n';
  content += '='.repeat(50) + '\n\n';
  
  messages.forEach((message, index) => {
    const timestamp = message.timestamp ? new Date(message.timestamp).toLocaleString() : 'Unknown time';
    const role = message.role === 'user' ? 'User' : 'AI Assistant';
    
    content += `${index + 1}. ${role} (${timestamp})\n`;
    content += `${message.content}\n`;
    content += '-'.repeat(30) + '\n\n';
  });
  
  content += '\nGenerated by DocAI Assistant\n';
  content += `Export Date: ${new Date().toLocaleString()}\n`;
  
  return content;
}

function formatContent(content, title) {
  let formatted = '';
  
  if (title) {
    formatted += `${title}\n`;
    formatted += '='.repeat(50) + '\n\n';
  }
  
  formatted += content;
  
  formatted += '\n\n---\n';
  formatted += 'Generated by DocAI Assistant\n';
  formatted += `Export Date: ${new Date().toLocaleString()}\n`;
  
  return formatted;
}

module.exports = router;
