const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

/**
 * PDF Action Handler
 * Generates PDF documents from content
 */

async function generatePDF(params, userId) {
  try {
    console.log('[PDF] Generating PDF:', { filename: params.filename, userId });
    console.log('[PDF] Received params:', JSON.stringify(params, null, 2));
    
    const { filename, content, query, chatHistory } = params;
    
    // Use chat history if available, otherwise use single content
    let pdfContent = content || 'Document content from DocAI';
    
    if (chatHistory && chatHistory.length > 0) {
      console.log('[PDF] Using chat history with', chatHistory.length, 'messages');
      console.log('[PDF] Chat history sample:', JSON.stringify(chatHistory.slice(0, 2), null, 2));
      
      // Format chat history for PDF
      pdfContent = 'DocAI Chat History\n' + '='.repeat(50) + '\n\n';
      
      chatHistory.forEach((message, index) => {
        const timestamp = message.timestamp ? new Date(message.timestamp).toLocaleString() : 'Unknown time';
        const role = message.role === 'user' ? 'User' : 'AI Assistant';
        
        pdfContent += `${index + 1}. ${role} (${timestamp})\n`;
        pdfContent += `${message.content}\n`;
        pdfContent += '-'.repeat(30) + '\n\n';
      });
      
      pdfContent += '\nGenerated by DocAI Assistant\n';
      pdfContent += `Export Date: ${new Date().toLocaleString()}\n`;
    } else {
      console.log('[PDF] Using single content (no chat history)');
      console.log('[PDF] chatHistory value:', chatHistory);
      console.log('[PDF] chatHistory length:', chatHistory ? chatHistory.length : 'null');
    }
    
    if (!pdfContent) {
      throw new Error('Content is required for PDF generation');
    }
    
    // Create uploads directory if it doesn't exist
    const uploadsDir = path.join(__dirname, '../uploads');
    try {
      await fs.promises.access(uploadsDir);
    } catch (error) {
      await fs.promises.mkdir(uploadsDir, { recursive: true });
    }
    
    // Generate unique filename
    const timestamp = Date.now();
    const pdfFilename = filename || `docai-export-${timestamp}.pdf`;
    const pdfPath = path.join(uploadsDir, pdfFilename);
    
    console.log('[PDF] Creating PDF at:', pdfPath);
    
    // Create PDF document
    const doc = new PDFDocument({
      margin: 50,
      size: 'A4'
    });
    
    // Pipe PDF to file
    const stream = fs.createWriteStream(pdfPath);
    doc.pipe(stream);
    
    // Add content to PDF
    doc.fontSize(20).text('DocAI Document Export', { align: 'center' });
    doc.moveDown();
    
    doc.fontSize(12).text(`Generated: ${new Date().toLocaleString()}`, { align: 'center' });
    doc.fontSize(12).text(`User ID: ${userId}`, { align: 'center' });
    doc.moveDown();
    
    if (query) {
      doc.fontSize(14).text('Original Query:', { underline: true });
      doc.fontSize(12).text(query);
      doc.moveDown();
    }
    
    // Add the main content (chat history or single response)
    doc.fontSize(14).text('Content:', { underline: true });
    doc.moveDown();
    
    // Split content into lines for better PDF formatting
    const contentLines = pdfContent.split('\n');
    doc.fontSize(12);
    
    contentLines.forEach(line => {
      if (line.trim()) {
        doc.text(line, { align: 'justify' });
        doc.moveDown(0.5);
      }
    });
    
    // Finalize PDF
    doc.end();
    
    // Wait for PDF to be written
    return new Promise((resolve, reject) => {
      stream.on('finish', async () => {
        try {
          // Get file stats
          const stats = await fs.promises.stat(pdfPath);
          
          console.log('[PDF] PDF generated successfully:', { 
            filename: pdfFilename, 
            size: stats.size,
            path: pdfPath 
          });
          
          resolve({
            status: 'success',
            message: `PDF generated successfully: ${pdfFilename}`,
            data: {
              filename: pdfFilename,
              path: pdfPath,
              size: stats.size,
              downloadUrl: `/api/downloads/${pdfFilename}`,
              timestamp: new Date().toISOString()
            }
          });
        } catch (error) {
          console.error('[PDF] Error getting file stats:', error);
          reject(error);
        }
      });
      
      stream.on('error', (error) => {
        console.error('[PDF] Stream error:', error);
        reject(new Error(`PDF generation failed: ${error.message}`));
      });
    });
    
  } catch (error) {
    console.error('[PDF] Error generating PDF:', error.message);
    throw new Error(`Failed to generate PDF: ${error.message}`);
  }
}

/**
 * Get PDF file for download
 */
async function getPDF(filename) {
  try {
    const pdfPath = path.join(__dirname, '../uploads', filename);
    
    // Check if file exists
    await fs.promises.access(pdfPath);
    
    return pdfPath;
  } catch (error) {
    throw new Error(`PDF file not found: ${filename}`);
  }
}

module.exports = {
  generatePDF,
  getPDF
};
